server:
  port: 50213
spring:
  application:
    name: MHXT-FastDFS
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sbblog?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 116924
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）

mybatis:
  mapper-locations: classpath:mapper/**/*.xml